//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfCheckout.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelfCheckout.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Device.
        /// </summary>
        internal static string AllDevice {
            get {
                return ResourceManager.GetString("AllDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch No..
        /// </summary>
        internal static string BranchNo {
            get {
                return ResourceManager.GetString("BranchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cannect to server! Please try again.
        /// </summary>
        internal static string CannotConnectToServer {
            get {
                return ResourceManager.GetString("CannotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shopping Card.
        /// </summary>
        internal static string ChangeShoppingCard {
            get {
                return ResourceManager.GetString("ChangeShoppingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker Management System.
        /// </summary>
        internal static string CheckerManagementSystem {
            get {
                return ResourceManager.GetString("CheckerManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete coupon?.
        /// </summary>
        internal static string ConfirmDeleteCoupon {
            get {
                return ResourceManager.GetString("ConfirmDeleteCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete item?.
        /// </summary>
        internal static string ConfirmDeleteItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use coupon?.
        /// </summary>
        internal static string ConfirmUseCoupon {
            get {
                return ResourceManager.GetString("ConfirmUseCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        internal static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown.
        /// </summary>
        internal static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string DateSlashTime {
            get {
                return ResourceManager.GetString("DateSlashTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info.
        /// </summary>
        internal static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device status.
        /// </summary>
        internal static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire on.
        /// </summary>
        internal static string ExpireOn {
            get {
                return ResourceManager.GetString("ExpireOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Customer.
        /// </summary>
        internal static string FilterCustomer {
            get {
                return ResourceManager.GetString("FilterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight No..
        /// </summary>
        internal static string FlightNo {
            get {
                return ResourceManager.GetString("FlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Admin.
        /// </summary>
        internal static string ForAdmin {
            get {
                return ResourceManager.GetString("ForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Detail.
        /// </summary>
        internal static string HolderDetail {
            get {
                return ResourceManager.GetString("HolderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Detail.
        /// </summary>
        internal static string ItemDetail {
            get {
                return ResourceManager.GetString("ItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine No..
        /// </summary>
        internal static string MachineNo {
            get {
                return ResourceManager.GetString("MachineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Detail.
        /// </summary>
        internal static string MoreDetail {
            get {
                return ResourceManager.GetString("MoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        internal static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My order.
        /// </summary>
        internal static string MyOrder {
            get {
                return ResourceManager.GetString("MyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string Occupied {
            get {
                return ResourceManager.GetString("Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied Device.
        /// </summary>
        internal static string OccupiedDevice {
            get {
                return ResourceManager.GetString("OccupiedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps.
        /// </summary>
        internal static string Opps {
            get {
                return ResourceManager.GetString("Opps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        internal static string OrderSummary {
            get {
                return ResourceManager.GetString("OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total.
        /// </summary>
        internal static string OrderTotal {
            get {
                return ResourceManager.GetString("OrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        internal static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No..
        /// </summary>
        internal static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username.
        /// </summary>
        internal static string PleaseEnterUserName {
            get {
                return ResourceManager.GetString("PleaseEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register!.
        /// </summary>
        internal static string PleaseRegister {
            get {
                return ResourceManager.GetString("PleaseRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan coupon.
        /// </summary>
        internal static string PleaseScanCoupon {
            get {
                return ResourceManager.GetString("PleaseScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan payment.
        /// </summary>
        internal static string PleaseScanPayment {
            get {
                return ResourceManager.GetString("PleaseScanPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Session.
        /// </summary>
        internal static string SaveSession {
            get {
                return ResourceManager.GetString("SaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this session?.
        /// </summary>
        internal static string SaveSessionConfirm {
            get {
                return ResourceManager.GetString("SaveSessionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Coupon.
        /// </summary>
        internal static string ScanCoupon {
            get {
                return ResourceManager.GetString("ScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan laser on QR Code.
        /// </summary>
        internal static string ScanLaserOnQRCode {
            get {
                return ResourceManager.GetString("ScanLaserOnQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan shopping card.
        /// </summary>
        internal static string ScanShoppingCard {
            get {
                return ResourceManager.GetString("ScanShoppingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select payment method.
        /// </summary>
        internal static string SelectPaymentMethod {
            get {
                return ResourceManager.GetString("SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session already finished..
        /// </summary>
        internal static string SessionAlreadyFinish {
            get {
                return ResourceManager.GetString("SessionAlreadyFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session history.
        /// </summary>
        internal static string SessionHistory {
            get {
                return ResourceManager.GetString("SessionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Key.
        /// </summary>
        internal static string SessionKey {
            get {
                return ResourceManager.GetString("SessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Card.
        /// </summary>
        internal static string ShoppingCard {
            get {
                return ResourceManager.GetString("ShoppingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shopping card is not activate!.
        /// </summary>
        internal static string ShoppingCardNotActivate {
            get {
                return ResourceManager.GetString("ShoppingCardNotActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart is empty.
        /// </summary>
        internal static string ShoppingCartEmpty {
            get {
                return ResourceManager.GetString("ShoppingCartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Login.
        /// </summary>
        internal static string StaffLogin {
            get {
                return ResourceManager.GetString("StaffLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start occupied.
        /// </summary>
        internal static string StartOccupied {
            get {
                return ResourceManager.GetString("StartOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Branch.
        /// </summary>
        internal static string SubBranch {
            get {
                return ResourceManager.GetString("SubBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see order in &quot;My Order&quot; menu.
        /// </summary>
        internal static string ThkForOrderDetail {
            get {
                return ResourceManager.GetString("ThkForOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order.
        /// </summary>
        internal static string ThkForOrderTitle {
            get {
                return ResourceManager.GetString("ThkForOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Use.
        /// </summary>
        internal static string TimeUse {
            get {
                return ResourceManager.GetString("TimeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Net.
        /// </summary>
        internal static string TotalNet {
            get {
                return ResourceManager.GetString("TotalNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid on.
        /// </summary>
        internal static string ValidOn {
            get {
                return ResourceManager.GetString("ValidOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
